### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tobedev** [schwifty42069/pmg#1]
If you get an error regarding versions/requirements not satisfied as follows:
"  Could not find a version that satisfies the requirement piptv_pmg (from versions: )
No matching distribution found for piptv_pmg "

Check your Python3 version installed, it should be 3.6 or above for the script to work.

**Comment by tobedev** [comment]
Actually, even after installing the required packages, I still get the same error :S

**Update:**
Solved by installing Python3.6 or above.

**Comment by schwifty42069** [comment]
Install it with pip, the requirements are built into the setup script. 
```
python3 -m pip install piptv_pmg
```

Make sure it's pulling version 0.1.0 from pypi. If it doesn't, disable pip's cache with the --no-cache-dir flag or add the version to the command with

```
python3 -m pip install piptv_pmg==0.1.0
```

**Comment by schwifty42069** [comment]
You're getting this error because I used a hacky way of making sure it finds the installed module directory, since it needs the resource directory of the package to get the included geckodriver binaries. (Which is why you have to install it with pip) I will patch it, but for now installing with pip should work just fine. I'm gonna close this, if you still can't get it running, open up a new issue and we'll figure it out.

**Comment by tobedev** [comment]
It turned out that Python3 version was 3.5.3 which is used by default on Debian stable (MX Linux 18.3), so by installing Python3.7 (Python 3.6+ is required) from the test repo, it ran successfully without errors.
And yes, I was installing it using the 'python3 -m pip install piptv_pmg' command.

I'll open up a new issue as I'm getting an error when I try to run the main script itself.

**Comment by schwifty42069** [comment]
I just patched the issue that caused your first problem, what is the new error?

**Comment by schwifty42069** [comment]
Try pip installing 0.1.1 now
